// import { MetricService } from './MetricService';
import { NominationsService } from './nominations/nominationsService';
let Zm1 = {
    essay: {
        id: '8fe154d3-0aa4-4fc4-bd97-c2e85ed67a45',
        text:
            '1825-1855 годы характеризуются правлением Николая 1. В этот период времени происходит очень много не маловажных событий для страны. Николай 1 взошел на престол после восстания декабристов. Трон должен был быть занятым Константином, старшим сыном Павла 1, но тот несколько раз письменно отрекался от него, говоря: « меня задушат также, как задушили отца», поэтому его занимает великий царь Николай Павлович 1.\nНиколай 1 проводил активную внешнюю и внутреннюю политику. Из внутренней политики рассмотрим остро стоящий крестьянский вопрос, на решение которого уделял внимание уже Александр 1. В этом вопросе все правители действовали осторожно, так как боялись той судьбы, которая постигла Павла 1, но как утверждают историки, ход событий по решению этого вопроса был совсем не последовательным. Правители боялись натиска, восстаний, различных протестов со стороны дворянства, которым было совсем невыгодно освобождать крестьян от зависимости. Николай 1 предпринял указ «об обязанных крестьянах» в 1842 году, который позволял помещикам добровольно прекращать крепостную зависимость крестьян, и провел инвертарную реформу в 1847 году, которая бы ограничила повинности крестьян, но оба этих изменений проигнорировали помещики, что и следовало ожидать.\nНиколай 1 также стремился привести в порядок российские законы. Соборное уложение еще 1649 года нуждалось в кодификации. Несомненно, в этом снова блеснет своими способностями и умом Михаил Сперанский, государственный деятель, который составит «Свод законов Российской Империи» в 1833 году.\nДавно стоящий крестьянский вопрос, его решение и кодификация законов были продиктованы общими причинами: застои в развитии страны, в какой-то мере консерватизм, стагнация, заинтересованность высших слоев общества была в том, чтобы были новые ясные, четкие законы; так же в интересах государства было раскрепощение крестьян, это было уже неизбежно, но каждый правитель боялся предпринять что-либо стоящее.\nВ годы 1825-1855 назревало очень много революционных идей, Россия нуждалась в реформах, но Николай 1 все это подавлял. Россия в эти годы участвовала во многих войнах и потерпела позорное поражение в Крымской войне и значительно ослабла, ко всему этому еще и потеряла влияние на Черном море, а значит в дальнейшем торговля России будет менее успешной.Но все же были и положительные моменты: развитие происходило в области экономики, была проведена финансовая реформа 1839-1843 годах, был введен серебряный рубль.\nЭпоха правления Николая 1 – это время, после которого вопрос о раскрепощении крестьян и усиление, восстановлении своей армии, флота встал еще острее.',
        meta: { theme: 'По периоду 1825-1855 годы', etc: '', subject: 'eng' },
        markups: [
            {
                id: 'test1',
                selections: [
                    {
                        id: 0,
                        tag: '',
                        type: 'проблема',
                        group: 'meaning',
                        comment: 'нейросетевая модель',
                        subtype: '',
                        correction: '',
                        explanation: 'хорошо выделен блок "проблема"',
                        endSelection: 82,
                        startSelection: 0,
                    },
                    {
                        id: 1,
                        tag: '',
                        type: 'прмнение',
                        group: 'meaning',
                        comment: 'нейросетевая модель',
                        subtype: '',
                        correction: '',
                        explanation: 'хорошо выделен блок "прмнение"',
                        endSelection: 82,
                        startSelection: 0,
                    },
                    {
                        id: 2,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: 'итеративное исправление',
                        subtype: '',
                        correction: 'not have',
                        explanation: 'грамматическая ошибка',
                        endSelection: 57,
                        startSelection: 54,
                    },
                    {
                        id: 3,
                        tag: '',
                        type: 'А.пункт',
                        group: 'error',
                        comment: 'итеративное исправление',
                        subtype: '',
                        correction: '.',
                        explanation: 'пунктуационная ошибка',
                        endSelection: 157,
                        startSelection: 156,
                    },
                    {
                        id: 4,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: 'итеративное исправление',
                        subtype: '',
                        correction: 'I am',
                        explanation: 'грамматическая ошибка',
                        endSelection: 185,
                        startSelection: 184,
                    },
                    {
                        id: 5,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: 'итеративное исправление',
                        subtype: 'видовр',
                        correction: 'studying',
                        explanation: 'грамматическая ошибка',
                        endSelection: 191,
                        startSelection: 186,
                    },
                    {
                        id: 6,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: ' итеративное исправление',
                        subtype: 'арт',
                        correction: '',
                        explanation: ' грамматическая ошибка',
                        endSelection: 209,
                        startSelection: 195,
                    },
                    {
                        id: 7,
                        tag: '',
                        type: 'А.орф',
                        group: 'error',
                        comment: 'итеративное исправление',
                        subtype: '',
                        correction: 'teams',
                        explanation: 'орфографическая ошибка',
                        endSelection: 285,
                        startSelection: 280,
                    },
                    {
                        id: 8,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: 'итеративное исправление',
                        subtype: 'видовр',
                        correction: 'help',
                        explanation: 'грамматическая ошибка',
                        endSelection: 291,
                        startSelection: 286,
                    },
                    {
                        id: 9,
                        tag: '',
                        type: 'А.лекс',
                        group: 'error',
                        comment: 'rule based model 345-1',
                        subtype: 'слово',
                        correction: 'cannot',
                        explanation: 'Possible typo',
                        endSelection: 397,
                        startSelection: 390,
                    },
                    {
                        id: 10,
                        tag: '',
                        type: 'лмнение',
                        group: 'meaning',
                        comment: 'нейросетевая модель',
                        subtype: '',
                        correction: '',
                        explanation: 'хорошо выделен блок "лмнение"',
                        endSelection: 546,
                        startSelection: 477,
                    },
                    {
                        id: 11,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: ' итеративное исправление',
                        subtype: '',
                        correction: 'platforms which',
                        explanation: ' грамматическая ошибка',
                        endSelection: 518,
                        startSelection: 502,
                    },
                    {
                        id: 12,
                        tag: '',
                        type: 'А.пункт',
                        group: 'error',
                        comment: ' итеративное исправление',
                        subtype: '',
                        correction: '. That',
                        explanation: ' пунктуационная ошибка',
                        endSelection: 739,
                        startSelection: 733,
                    },
                    {
                        id: 13,
                        tag: '',
                        type: 'А.пункт',
                        group: 'error',
                        comment: 'итеративное исправление',
                        subtype: '',
                        correction: 'year ,',
                        explanation: 'пунктуационная ошибка',
                        endSelection: 899,
                        startSelection: 895,
                    },
                    {
                        id: 14,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: ' итеративное исправление',
                        subtype: 'пред',
                        correction: 'join us',
                        explanation: ' грамматическая ошибка',
                        endSelection: 921,
                        startSelection: 911,
                    },
                    {
                        id: 15,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: ' итеративное исправление',
                        subtype: 'пред',
                        correction: 'how to work',
                        explanation: ' грамматическая ошибка',
                        endSelection: 971,
                        startSelection: 963,
                    },
                    {
                        id: 16,
                        tag: '',
                        type: 'аргумент',
                        group: 'meaning',
                        comment: 'нейросетевая модель',
                        subtype: '',
                        correction: '',
                        explanation: 'хорошо выделен блок "аргумент"',
                        endSelection: 1064,
                        startSelection: 983,
                    },
                    {
                        id: 17,
                        tag: '',
                        type: 'обоснование',
                        group: 'meaning',
                        comment: 'нейросетевая модель',
                        subtype: '',
                        correction: '',
                        explanation: 'хорошо выделен блок "обоснование"',
                        endSelection: 1157,
                        startSelection: 1065,
                    },
                    {
                        id: 18,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: 'итеративное исправление',
                        subtype: '',
                        correction: 'allows us',
                        explanation: 'грамматическая ошибка',
                        endSelection: 1074,
                        startSelection: 1068,
                    },
                    {
                        id: 19,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: 'rule based model 9-1',
                        subtype: 'видовр',
                        correction: 'making',
                        explanation: 'Grammatical problem: use a gerund',
                        endSelection: 1082,
                        startSelection: 1075,
                    },
                    {
                        id: 20,
                        tag: '',
                        type: 'А.пункт',
                        group: 'error',
                        comment: 'итеративное исправление',
                        subtype: '',
                        correction: 'that ,',
                        explanation: 'пунктуационная ошибка',
                        endSelection: 1194,
                        startSelection: 1190,
                    },
                    {
                        id: 21,
                        tag: '',
                        type: 'А.пункт',
                        group: 'error',
                        comment: 'итеративное исправление',
                        subtype: '',
                        correction: 'phones ,',
                        explanation: 'пунктуационная ошибка',
                        endSelection: 1215,
                        startSelection: 1209,
                    },
                    {
                        id: 22,
                        tag: '',
                        type: 'А.грамм',
                        group: 'error',
                        comment: 'rule based model 45-1',
                        subtype: 'арт',
                        correction: 'An SMS',
                        explanation: 'Article missing',
                        endSelection: 1247,
                        startSelection: 1244,
                    },
                    {
                        id: 23,
                        tag: '',
                        type: 'вывод',
                        group: 'meaning',
                        comment: 'нейросетевая модель',
                        subtype: '',
                        correction: '',
                        explanation: 'хорошо выделен блок "вывод"',
                        endSelection: 1389,
                        startSelection: 1263,
                    },
                    {
                        id: 24,
                        tag: '',
                        type: 'А.уров',
                        group: 'error',
                        comment: 'rule based model 87-1',
                        subtype: 'некорр',
                        correction: '',
                        explanation: 'Possibly needless word',
                        endSelection: 1282,
                        startSelection: 1278,
                    },
                ],
                criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
                metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
            },
            {
                id: 'test2',
                selections: [
                    {
                        id: 8104,
                        tag: '',
                        type: 'ЛМНЕНИЕ',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 1262,
                        startSelection: 1158,
                    },
                    {
                        id: 1811,
                        tag: '',
                        type: 'ВЫВОД',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 1389,
                        startSelection: 1263,
                    },
                    {
                        id: 9624,
                        tag: '',
                        type: 'ПРОБЛЕМА',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 179,
                        startSelection: 0,
                    },
                    {
                        id: 5512,
                        tag: '',
                        type: 'АРГУМЕНТ',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 269,
                        startSelection: 180,
                    },
                    {
                        id: 4890,
                        tag: '',
                        type: 'АРГУМЕНТ',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 476,
                        startSelection: 270,
                    },
                    {
                        id: 4629,
                        tag: '',
                        type: 'АРГУМЕНТ',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 772,
                        startSelection: 633,
                    },
                    {
                        id: 7230,
                        tag: '',
                        type: 'АРГУМЕНТ',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 1157,
                        startSelection: 773,
                    },
                    {
                        id: 8660,
                        tag: '',
                        type: 'А.ПРОБЛ',
                        group: 'error',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 179,
                        startSelection: 0,
                    },
                    {
                        id: 3032,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'стяж',
                        correction: '',
                        explanation: '',
                        endSelection: 162,
                        startSelection: 158,
                    },
                    {
                        id: 7215,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'арт',
                        correction: 'at university',
                        explanation: '',
                        endSelection: 209,
                        startSelection: 192,
                    },
                    {
                        id: 4627,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'стяж',
                        correction: '',
                        explanation: '',
                        endSelection: 310,
                        startSelection: 306,
                    },
                    {
                        id: 5224,
                        tag: '',
                        type: 'АРГУМЕНТ',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 632,
                        startSelection: 477,
                    },
                    {
                        id: 6699,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'стяж',
                        correction: 'cannot',
                        explanation: '',
                        endSelection: 397,
                        startSelection: 390,
                    },
                    {
                        id: 271,
                        tag: '',
                        type: 'А.ЛЕКС',
                        group: 'error',
                        comment: '',
                        subtype: 'конт',
                        correction: 'maintain',
                        explanation: '',
                        endSelection: 531,
                        startSelection: 527,
                    },
                    {
                        id: 3634,
                        tag: '98gg9',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'стяж',
                        correction: '',
                        explanation: '',
                        endSelection: 646,
                        startSelection: 643,
                    },
                    {
                        id: 1528,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'стяж',
                        correction: '',
                        explanation: '',
                        endSelection: 741,
                        startSelection: 735,
                    },
                    {
                        id: 4518,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'пред',
                        correction: 'join us ',
                        explanation: '',
                        endSelection: 921,
                        startSelection: 911,
                    },
                    {
                        id: 3812,
                        tag: '',
                        type: 'А.УРОВ',
                        group: 'error',
                        comment: '',
                        subtype: 'некорр',
                        correction: 'how to work with them',
                        explanation: '',
                        endSelection: 981,
                        startSelection: 963,
                    },
                    {
                        id: 986,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'сниж',
                        correction: '',
                        explanation: '',
                        endSelection: 1041,
                        startSelection: 1034,
                    },
                    {
                        id: 2062,
                        tag: '98gg9',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'стяж',
                        correction: '',
                        explanation: '',
                        endSelection: 1272,
                        startSelection: 1269,
                    },
                ],
                criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
                metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
                isExpert: true,
            },
            // {
            //     id: 'qwe123',
            //     // selections: [{id: 0, "tag": "", type: "А.СТИЛЬ", group: "error", comment: "", subtype: "ритор", correction: "", explanation: "Стилистическая ошибка. Риторический вопрос.", endSelection: 55, startSelection: 0}, {id: 348, "tag": "", type: "А.СТИЛЬ", group: "error", comment: "", subtype: "ритор", correction: "", explanation: "Стилистическая ошибка. Риторический вопрос.", endSelection: 331, startSelection: 285}, {id: 395, "tag": "", type: "А.ГРАММ", group: "error", comment: "", subtype: "арт", correction: "the modern society", explanation: "Артикль", endSelection: 330, startSelection: 316}, {id: 855, "tag": "", type: "А.СТИЛЬ", group: "error", comment: "", subtype: "стяж", correction: "", explanation: "Стилистическая ошибка. Стяженные формы.", endSelection: 690, startSelection: 684}, {id: 940, "tag": "", type: "А.ПУНКТ", group: "error", comment: "", subtype: "", correction: "news.", explanation: "Пунктуационная ошибка.", endSelection: 718, startSelection: 711}, {id: 1126, "tag": "", type: "А.ПУНКТ", group: "error", comment: "", subtype: "", correction: "scheduled", explanation: "Пунктуационная ошибка.", endSelection: 864, startSelection: 854}, {id: 1221, "tag": "", type: "А.ЛОГИКА", group: "error", comment: "", subtype: "", correction: "", explanation: "Логическая ошибка", endSelection: 979, startSelection: 902}, {id: 1441, "tag": "", type: "А.ГРАММ", group: "error", comment: "", subtype: "поряд", correction: "it will be organized", explanation: "Порядок слов в предложении", endSelection: 1110, startSelection: 1090}],
            //     selections: [
            //         {
            //             id: 0,
            //             tag: '',
            //             type: 'А.СТИЛЬ',
            //             group: 'error',
            //             comment: '',
            //             subtype: 'ритор',
            //             correction: '',
            //             explanation: 'Стилистическая ошибка. Риторический вопрос.',
            //             endSelection: 55,
            //             startSelection: 0,
            //         },
            //         {
            //             id: 0,
            //             tag: '',
            //             type: 'А.СТИЛЬ',
            //             group: 'error',
            //             comment: '',
            //             subtype: 'ритор',
            //             correction: '',
            //             explanation: 'Стилистическая ошибка. Риторический вопрос.',
            //             endSelection: 55,
            //             startSelection: 0,
            //         },
            //         {
            //             id: 0,
            //             tag: '',
            //             type: 'А.СТИЛЬ',
            //             group: 'error',
            //             comment: '',
            //             subtype: 'ритор',
            //             correction: '',
            //             explanation: 'Стилистическая ошибка. Риторический вопрос.',
            //             endSelection: 431,
            //             startSelection: 321,
            //         },
            //         {
            //             id: 0,
            //             tag: '',
            //             type: 'А.СТИЛЬ',
            //             group: 'error',
            //             comment: '',
            //             subtype: 'ритор',
            //             correction: '',
            //             explanation: 'Стилистическая ошибка. Риторический вопрос.',
            //             endSelection: 228,
            //             startSelection: 114,
            //         },
            //     ],
            //     criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
            //     metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
            // },
        ],
    },
};
let p = new NominationsService().calculate(Zm1);
console.log(JSON.stringify(p, null, 2));
