import { MetricService } from './MetricService';
// let Zm = {
//     essay: {
//         id: '8fe154d3-0aa4-4fc4-bd97-c2e85ed67a45',
//         text:
//             '1825-1855 годы характеризуются правлением Николая 1. В этот период времени происходит очень много не маловажных событий для страны. Николай 1 взошел на престол после восстания декабристов. Трон должен был быть занятым Константином, старшим сыном Павла 1, но тот несколько раз письменно отрекался от него, говоря: « меня задушат также, как задушили отца», поэтому его занимает великий царь Николай Павлович 1.\nНиколай 1 проводил активную внешнюю и внутреннюю политику. Из внутренней политики рассмотрим остро стоящий крестьянский вопрос, на решение которого уделял внимание уже Александр 1. В этом вопросе все правители действовали осторожно, так как боялись той судьбы, которая постигла Павла 1, но как утверждают историки, ход событий по решению этого вопроса был совсем не последовательным. Правители боялись натиска, восстаний, различных протестов со стороны дворянства, которым было совсем невыгодно освобождать крестьян от зависимости. Николай 1 предпринял указ «об обязанных крестьянах» в 1842 году, который позволял помещикам добровольно прекращать крепостную зависимость крестьян, и провел инвертарную реформу в 1847 году, которая бы ограничила повинности крестьян, но оба этих изменений проигнорировали помещики, что и следовало ожидать.\nНиколай 1 также стремился привести в порядок российские законы. Соборное уложение еще 1649 года нуждалось в кодификации. Несомненно, в этом снова блеснет своими способностями и умом Михаил Сперанский, государственный деятель, который составит «Свод законов Российской Империи» в 1833 году.\nДавно стоящий крестьянский вопрос, его решение и кодификация законов были продиктованы общими причинами: застои в развитии страны, в какой-то мере консерватизм, стагнация, заинтересованность высших слоев общества была в том, чтобы были новые ясные, четкие законы; так же в интересах государства было раскрепощение крестьян, это было уже неизбежно, но каждый правитель боялся предпринять что-либо стоящее.\nВ годы 1825-1855 назревало очень много революционных идей, Россия нуждалась в реформах, но Николай 1 все это подавлял. Россия в эти годы участвовала во многих войнах и потерпела позорное поражение в Крымской войне и значительно ослабла, ко всему этому еще и потеряла влияние на Черном море, а значит в дальнейшем торговля России будет менее успешной.Но все же были и положительные моменты: развитие происходило в области экономики, была проведена финансовая реформа 1839-1843 годах, был введен серебряный рубль.\nЭпоха правления Николая 1 – это время, после которого вопрос о раскрепощении крестьян и усиление, восстановлении своей армии, флота встал еще острее.',
//         meta: { theme: 'По периоду 1825-1855 годы', etc: '', subject: 'hist' },
//         markups: [
//             {
//                 id: 'qwe',
//                 selections: [{id: 626, tag: "", type: "Р.МЕСТ", group: "error", comment: "", subtype: "", correction: "", explanation: "", endSelection: 143, startSelection: 129}, {id: 941, tag: "", type: "Ф.ИСКАЖ", group: "error", comment: "", subtype: "", correction: "", explanation: "", endSelection: 589, startSelection: 550}, {id: 774, tag: "", type: "Г.СЛОВ", group: "error", comment: "", subtype: "сущ", correction: "", explanation: "", endSelection: 977, startSelection: 952}, {id: 276, tag: "", type: "Р.ОНИМ", group: "error", comment: "", subtype: "син", correction: "", explanation: "", endSelection: 1213, startSelection: 1194}, {id: 304, tag: "", type: "Р.ЗНАЧ", group: "error", comment: "", subtype: "несвой", correction: "", explanation: "", endSelection: 1341, startSelection: 1329}, {id: 917, tag: "", type: "Р.НЕПОЛН", group: "error", comment: "", subtype: "", correction: "", explanation: "", endSelection: 1811, startSelection: 1782}, {id: 310, tag: "", type: "Р.ДВУСМ", group: "error", comment: "", subtype: "омон", correction: "", explanation: "", endSelection: 1919, startSelection: 1889}, {id: 277, tag: "", type: "Р.ДВУСМ", group: "error", comment: "", subtype: "омон", correction: "", explanation: "", endSelection: 2000, startSelection: 1970}, {id: 179, tag: "", type: "Р.ПОВТОР", group: "error", comment: "", subtype: "", correction: "", explanation: "", endSelection: 2544, startSelection: 2539}, {id: 65, tag: "", type: "Р.ДВУСМ", group: "error", comment: "", subtype: "омон", correction: "", explanation: "", endSelection: 2972, startSelection: 2957}],
//                 criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
//                 metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
//                 isExpert: true,
//             },
//             {
//                 id: 'qwe12',
//                 selections: [{id: 350, tag: "", type: "ПРОБЛЕМА", group: "meaning", comment: "", subtype: "", correction: "", explanation: "", endSelection: 197, startSelection: 0}, {id: 699, tag: "", type: "ПРИМЕР", group: "meaning", comment: "", subtype: "", correction: "", explanation: "", endSelection: 668, startSelection: 198}, {id: 478, tag: "", type: "ПОЯСНЕНИЕ", group: "meaning", comment: "", subtype: "", correction: "", explanation: "", endSelection: 826, startSelection: 669}, {id: 924, tag: "", type: "ПОЗИЦИЯ", group: "meaning", comment: "", subtype: "", correction: "", explanation: "", endSelection: 1661, startSelection: 1372}, {id: 829, tag: "", type: "ОТНОШЕНИЕ", group: "meaning", comment: "", subtype: "", correction: "", explanation: "", endSelection: 2916, startSelection: 1662}, {id: 642, tag: "", type: "Р.ЛИШН", group: "error", comment: "", subtype: "лишн", correction: "В своём тексте", explanation: "", endSelection: 156, startSelection: 122}, {id: 578, tag: "", type: "Р.СОЧЕТ", group: "error", comment: "", subtype: "", correction: "", explanation: "", endSelection: 197, startSelection: 173}, {id: 765, tag: "", type: "Р.ЗНАЧ", group: "error", comment: "", subtype: "термин", correction: "Тема и проблема - неравноценные понятия", explanation: "", endSelection: 405, startSelection: 378}, {id: 949, tag: "", type: "Г.СЛОЖН", group: "error", comment: "", subtype: "", correction: "Каким", explanation: "", endSelection: 494, startSelection: 448}, {id: 254, tag: "", type: "Р.ЗНАЧ", group: "error", comment: "", subtype: "термин", correction: "Утвердиться ", explanation: "", endSelection: 668, startSelection: 630}, {id: 85, tag: "", type: "ПРИМЕР", group: "meaning", comment: "", subtype: "", correction: "", explanation: "", endSelection: 1108, startSelection: 827}, {id: 149, tag: "", type: "ПОЯСНЕНИЕ", group: "meaning", comment: "", subtype: "", correction: "", explanation: "", endSelection: 1239, startSelection: 1109}, {id: 325, tag: "", type: "СВЯЗЬ", group: "meaning", comment: "", subtype: "", correction: "", explanation: "", endSelection: 1371, startSelection: 1240}, {id: 761, tag: "", type: "Р.ЛИШН", group: "error", comment: "", subtype: "лишн", correction: "Эти", explanation: "", endSelection: 1256, startSelection: 1240}, {id: 21, tag: "", type: "Г.УПР", group: "error", comment: "", subtype: "упр", correction: "Для моей", explanation: "", endSelection: 2009, startSelection: 1970}, {id: 135, tag: "", type: "Ф.НАЗВАН", group: "error", comment: "", subtype: "автор", correction: "Брэдбери", explanation: "", endSelection: 2029, startSelection: 2019}, {id: 588, tag: "", type: "Р.ПОВТОР", group: "error", comment: "", subtype: "", correction: "Этому, этом", explanation: "", endSelection: 2370, startSelection: 2321}, {id: 447, tag: "", type: "Ф.НАЗВАН", group: "error", comment: "", subtype: "автор", correction: "", explanation: "", endSelection: 2853, startSelection: 2843}],
//                 criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
//                 metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
//                 isExpert: true,
//             },
//             {
//                 id: 'qwe123',
//                 selections: [{id: 111, tag: "", type: "П.проблема", group: "meaning", comment: "", subtype: "", correction: "", explanation: "", endSelection: 20, startSelection: 10}],
//                 criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
//                 metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
//             }
//         ]
//     }
// }
let Zm = {
    essay: {
        id: '8fe154d3-0aa4-4fc4-bd97-c2e85ed67a45',
        text:
            '1825-1855 годы характеризуются правлением Николая 1. В этот период времени происходит очень много не маловажных событий для страны. Николай 1 взошел на престол после восстания декабристов. Трон должен был быть занятым Константином, старшим сыном Павла 1, но тот несколько раз письменно отрекался от него, говоря: « меня задушат также, как задушили отца», поэтому его занимает великий царь Николай Павлович 1.\nНиколай 1 проводил активную внешнюю и внутреннюю политику. Из внутренней политики рассмотрим остро стоящий крестьянский вопрос, на решение которого уделял внимание уже Александр 1. В этом вопросе все правители действовали осторожно, так как боялись той судьбы, которая постигла Павла 1, но как утверждают историки, ход событий по решению этого вопроса был совсем не последовательным. Правители боялись натиска, восстаний, различных протестов со стороны дворянства, которым было совсем невыгодно освобождать крестьян от зависимости. Николай 1 предпринял указ «об обязанных крестьянах» в 1842 году, который позволял помещикам добровольно прекращать крепостную зависимость крестьян, и провел инвертарную реформу в 1847 году, которая бы ограничила повинности крестьян, но оба этих изменений проигнорировали помещики, что и следовало ожидать.\nНиколай 1 также стремился привести в порядок российские законы. Соборное уложение еще 1649 года нуждалось в кодификации. Несомненно, в этом снова блеснет своими способностями и умом Михаил Сперанский, государственный деятель, который составит «Свод законов Российской Империи» в 1833 году.\nДавно стоящий крестьянский вопрос, его решение и кодификация законов были продиктованы общими причинами: застои в развитии страны, в какой-то мере консерватизм, стагнация, заинтересованность высших слоев общества была в том, чтобы были новые ясные, четкие законы; так же в интересах государства было раскрепощение крестьян, это было уже неизбежно, но каждый правитель боялся предпринять что-либо стоящее.\nВ годы 1825-1855 назревало очень много революционных идей, Россия нуждалась в реформах, но Николай 1 все это подавлял. Россия в эти годы участвовала во многих войнах и потерпела позорное поражение в Крымской войне и значительно ослабла, ко всему этому еще и потеряла влияние на Черном море, а значит в дальнейшем торговля России будет менее успешной.Но все же были и положительные моменты: развитие происходило в области экономики, была проведена финансовая реформа 1839-1843 годах, был введен серебряный рубль.\nЭпоха правления Николая 1 – это время, после которого вопрос о раскрепощении крестьян и усиление, восстановлении своей армии, флота встал еще острее.',
        meta: { theme: 'По периоду 1825-1855 годы', etc: '', subject: 'hist' },
        markups: [
            {
                id: 'qwe',
                selections: [
                    {
                        id: 0,
                        tag: '',
                        type: 'А.АСПЕКТ',
                        group: 'error',
                        comment: '',
                        subtype: 'нераск',
                        correction: '',
                        explanation: 'Аспект не раскрыт.',
                        endSelection: 331,
                        startSelection: 0,
                    },
                    {
                        id: 18,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 55,
                        startSelection: 0,
                    },
                    {
                        id: 366,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 331,
                        startSelection: 285,
                    },
                    {
                        id: 498,
                        tag: '',
                        type: 'А.АСПЕКТ',
                        group: 'error',
                        comment: '',
                        subtype: 'нераск',
                        correction: '',
                        explanation: 'Аспект не раскрыт.',
                        endSelection: 663,
                        startSelection: 332,
                    },
                    {
                        id: 890,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'стяж',
                        correction: 'did not',
                        explanation: 'Стилистическая ошибка. Стяженные формы.',
                        endSelection: 690,
                        startSelection: 684,
                    },
                    {
                        id: 1079,
                        tag: '',
                        type: 'А.ЛЕКС',
                        group: 'error',
                        comment: '',
                        subtype: 'конт',
                        correction: 'started',
                        explanation:
                            'Лексическая ошибка. Неправильное употребление слова в контексте',
                        endSelection: 818,
                        startSelection: 806,
                    },
                    {
                        id: 1295,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'арт',
                        correction: 'a',
                        explanation: 'Артикль',
                        endSelection: 943,
                        startSelection: 932,
                    },
                    {
                        id: 1477,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'поряд',
                        correction: 'how it will',
                        explanation: 'Порядок слов в предложении',
                        endSelection: 1097,
                        startSelection: 1086,
                    },
                    {
                        id: 1598,
                        tag: '',
                        type: 'А.УРОВ',
                        group: 'error',
                        comment: '',
                        subtype: 'некорр',
                        correction: '',
                        explanation: 'Некорректное использование грамматических средств',
                        endSelection: 1187,
                        startSelection: 1148,
                    },
                ],
                criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
                metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
                isExpert: true,
            },
            {
                id: 'qwe12',
                selections: [
                    {
                        id: 0,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 55,
                        startSelection: 0,
                    },
                    {
                        id: 348,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 331,
                        startSelection: 285,
                    },
                    {
                        id: 395,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'арт',
                        correction: 'the modern society',
                        explanation: 'Артикль',
                        endSelection: 330,
                        startSelection: 316,
                    },
                    {
                        id: 855,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'стяж',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Стяженные формы.',
                        endSelection: 690,
                        startSelection: 684,
                    },
                    {
                        id: 940,
                        tag: '',
                        type: 'А.ПУНКТ',
                        group: 'error',
                        comment: '',
                        subtype: '',
                        correction: 'news.',
                        explanation: 'Пунктуационная ошибка.',
                        endSelection: 718,
                        startSelection: 711,
                    },
                    {
                        id: 1126,
                        tag: '',
                        type: 'А.ПУНКТ',
                        group: 'error',
                        comment: '',
                        subtype: '',
                        correction: 'scheduled',
                        explanation: 'Пунктуационная ошибка.',
                        endSelection: 864,
                        startSelection: 854,
                    },
                    {
                        id: 1221,
                        tag: '',
                        type: 'А.ЛОГИКА',
                        group: 'error',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: 'Логическая ошибка',
                        endSelection: 979,
                        startSelection: 902,
                    },
                    {
                        id: 1441,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'поряд',
                        correction: 'it will be organized',
                        explanation: 'Порядок слов в предложении',
                        endSelection: 1110,
                        startSelection: 1090,
                    },
                ],
                criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
                metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
                isExpert: true,
            },
            {
                id: 'qwe12',
                selections: [
                    {
                        id: 0,
                        tag: '',
                        type: 'АРГУМЕНТ',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 154,
                        startSelection: 56,
                    },
                    {
                        id: 1,
                        tag: '',
                        type: 'АРГУМЕНТ',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 330,
                        startSelection: 156,
                    },
                    {
                        id: 2,
                        tag: '',
                        type: 'АРГУМЕНТ',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 1136,
                        startSelection: 1072,
                    },
                    {
                        id: 3,
                        tag: '',
                        type: 'АРГУМЕНТ',
                        group: 'meaning',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: '',
                        endSelection: 1179,
                        startSelection: 1138,
                    },
                    {
                        id: 4,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'арт',
                        correction: 'the worsening',
                        explanation: 'the worsening',
                        endSelection: 417,
                        startSelection: 407,
                    },
                    {
                        id: 5,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'арт',
                        correction: 'the ecological',
                        explanation: 'the ecological',
                        endSelection: 431,
                        startSelection: 420,
                    },
                ],
                criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
                metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
            },
        ],
    },
};
let Zm1 = {
    essay: {
        id: '8fe154d3-0aa4-4fc4-bd97-c2e85ed67a45',
        text:
            '1825-1855 годы характеризуются правлением Николая 1. В этот период времени происходит очень много не маловажных событий для страны. Николай 1 взошел на престол после восстания декабристов. Трон должен был быть занятым Константином, старшим сыном Павла 1, но тот несколько раз письменно отрекался от него, говоря: « меня задушат также, как задушили отца», поэтому его занимает великий царь Николай Павлович 1.\nНиколай 1 проводил активную внешнюю и внутреннюю политику. Из внутренней политики рассмотрим остро стоящий крестьянский вопрос, на решение которого уделял внимание уже Александр 1. В этом вопросе все правители действовали осторожно, так как боялись той судьбы, которая постигла Павла 1, но как утверждают историки, ход событий по решению этого вопроса был совсем не последовательным. Правители боялись натиска, восстаний, различных протестов со стороны дворянства, которым было совсем невыгодно освобождать крестьян от зависимости. Николай 1 предпринял указ «об обязанных крестьянах» в 1842 году, который позволял помещикам добровольно прекращать крепостную зависимость крестьян, и провел инвертарную реформу в 1847 году, которая бы ограничила повинности крестьян, но оба этих изменений проигнорировали помещики, что и следовало ожидать.\nНиколай 1 также стремился привести в порядок российские законы. Соборное уложение еще 1649 года нуждалось в кодификации. Несомненно, в этом снова блеснет своими способностями и умом Михаил Сперанский, государственный деятель, который составит «Свод законов Российской Империи» в 1833 году.\nДавно стоящий крестьянский вопрос, его решение и кодификация законов были продиктованы общими причинами: застои в развитии страны, в какой-то мере консерватизм, стагнация, заинтересованность высших слоев общества была в том, чтобы были новые ясные, четкие законы; так же в интересах государства было раскрепощение крестьян, это было уже неизбежно, но каждый правитель боялся предпринять что-либо стоящее.\nВ годы 1825-1855 назревало очень много революционных идей, Россия нуждалась в реформах, но Николай 1 все это подавлял. Россия в эти годы участвовала во многих войнах и потерпела позорное поражение в Крымской войне и значительно ослабла, ко всему этому еще и потеряла влияние на Черном море, а значит в дальнейшем торговля России будет менее успешной.Но все же были и положительные моменты: развитие происходило в области экономики, была проведена финансовая реформа 1839-1843 годах, был введен серебряный рубль.\nЭпоха правления Николая 1 – это время, после которого вопрос о раскрепощении крестьян и усиление, восстановлении своей армии, флота встал еще острее.',
        meta: { theme: 'По периоду 1825-1855 годы', etc: '', subject: 'hist' },
        markups: [
            {
                id: 'qwe1232',
                selections: [
                    {
                        id: 0,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 55,
                        startSelection: 0,
                    },
                    {
                        id: 348,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 331,
                        startSelection: 285,
                    },
                    {
                        id: 395,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'арт',
                        correction: 'the modern society',
                        explanation: 'Артикль',
                        endSelection: 330,
                        startSelection: 316,
                    },
                    {
                        id: 855,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'стяж',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Стяженные формы.',
                        endSelection: 690,
                        startSelection: 684,
                    },
                    {
                        id: 940,
                        tag: '',
                        type: 'А.ПУНКТ',
                        group: 'error',
                        comment: '',
                        subtype: '',
                        correction: 'news.',
                        explanation: 'Пунктуационная ошибка.',
                        endSelection: 718,
                        startSelection: 711,
                    },
                    {
                        id: 1126,
                        tag: '',
                        type: 'А.ПУНКТ',
                        group: 'error',
                        comment: '',
                        subtype: '',
                        correction: 'scheduled',
                        explanation: 'Пунктуационная ошибка.',
                        endSelection: 864,
                        startSelection: 854,
                    },
                    {
                        id: 1221,
                        tag: '',
                        type: 'А.ЛОГИКА',
                        group: 'error',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: 'Логическая ошибка',
                        endSelection: 979,
                        startSelection: 902,
                    },
                    {
                        id: 1441,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'поряд',
                        correction: 'it will be organized',
                        explanation: 'Порядок слов в предложении',
                        endSelection: 1110,
                        startSelection: 1090,
                    },
                ],
                criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
                metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
                isExpert: true,
            },
            {
                id: 'qwe12',
                selections: [
                    {
                        id: 0,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 55,
                        startSelection: 0,
                    },
                    {
                        id: 348,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 331,
                        startSelection: 285,
                    },
                    {
                        id: 395,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'арт',
                        correction: 'the modern society',
                        explanation: 'Артикль',
                        endSelection: 330,
                        startSelection: 316,
                    },
                    {
                        id: 855,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'стяж',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Стяженные формы.',
                        endSelection: 690,
                        startSelection: 684,
                    },
                    {
                        id: 940,
                        tag: '',
                        type: 'А.ПУНКТ',
                        group: 'error',
                        comment: '',
                        subtype: '',
                        correction: 'news.',
                        explanation: 'Пунктуационная ошибка.',
                        endSelection: 718,
                        startSelection: 711,
                    },
                    {
                        id: 1126,
                        tag: '',
                        type: 'А.ПУНКТ',
                        group: 'error',
                        comment: '',
                        subtype: '',
                        correction: 'scheduled',
                        explanation: 'Пунктуационная ошибка.',
                        endSelection: 864,
                        startSelection: 854,
                    },
                    {
                        id: 1221,
                        tag: '',
                        type: 'А.ЛОГИКА',
                        group: 'error',
                        comment: '',
                        subtype: '',
                        correction: '',
                        explanation: 'Логическая ошибка',
                        endSelection: 979,
                        startSelection: 902,
                    },
                    {
                        id: 1441,
                        tag: '',
                        type: 'А.ГРАММ',
                        group: 'error',
                        comment: '',
                        subtype: 'поряд',
                        correction: 'it will be organized',
                        explanation: 'Порядок слов в предложении',
                        endSelection: 1110,
                        startSelection: 1090,
                    },
                ],
                criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
                metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
                isExpert: true,
            },
            {
                id: 'qwe123',
                // selections: [{id: 0, "tag": "", type: "А.СТИЛЬ", group: "error", comment: "", subtype: "ритор", correction: "", explanation: "Стилистическая ошибка. Риторический вопрос.", endSelection: 55, startSelection: 0}, {id: 348, "tag": "", type: "А.СТИЛЬ", group: "error", comment: "", subtype: "ритор", correction: "", explanation: "Стилистическая ошибка. Риторический вопрос.", endSelection: 331, startSelection: 285}, {id: 395, "tag": "", type: "А.ГРАММ", group: "error", comment: "", subtype: "арт", correction: "the modern society", explanation: "Артикль", endSelection: 330, startSelection: 316}, {id: 855, "tag": "", type: "А.СТИЛЬ", group: "error", comment: "", subtype: "стяж", correction: "", explanation: "Стилистическая ошибка. Стяженные формы.", endSelection: 690, startSelection: 684}, {id: 940, "tag": "", type: "А.ПУНКТ", group: "error", comment: "", subtype: "", correction: "news.", explanation: "Пунктуационная ошибка.", endSelection: 718, startSelection: 711}, {id: 1126, "tag": "", type: "А.ПУНКТ", group: "error", comment: "", subtype: "", correction: "scheduled", explanation: "Пунктуационная ошибка.", endSelection: 864, startSelection: 854}, {id: 1221, "tag": "", type: "А.ЛОГИКА", group: "error", comment: "", subtype: "", correction: "", explanation: "Логическая ошибка", endSelection: 979, startSelection: 902}, {id: 1441, "tag": "", type: "А.ГРАММ", group: "error", comment: "", subtype: "поряд", correction: "it will be organized", explanation: "Порядок слов в предложении", endSelection: 1110, startSelection: 1090}],
                selections: [
                    {
                        id: 0,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 55,
                        startSelection: 0,
                    },
                    {
                        id: 0,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 55,
                        startSelection: 0,
                    },
                    {
                        id: 0,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 431,
                        startSelection: 321,
                    },
                    {
                        id: 0,
                        tag: '',
                        type: 'А.СТИЛЬ',
                        group: 'error',
                        comment: '',
                        subtype: 'ритор',
                        correction: '',
                        explanation: 'Стилистическая ошибка. Риторический вопрос.',
                        endSelection: 228,
                        startSelection: 114,
                    },
                ],
                criteria: { K1: 2, K2: 0, K3: 0, K4: -1, K5: 1, K6: 1, K7: 0 },
                metrics: { M1: 0, M2: 0, M3: 0, M4: 0, M5: 0, M6: 0, M7: 0 },
            },
        ],
    },
};

let p = new MetricService().calculate(Zm1);
console.log(JSON.stringify(p, null, 2));
